name: "hellonil"
mode: "release"
port: 8084
version: "v0.0.1"
start_time: "2023-01-30"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "douyin.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "gz-cdb-0r0kvcx1.sql.tencentcdb.com"
  port: 63930
  user: "root"
  password: "HELLOnil123++"
  dbname: "hellonil"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 101.35.43.151
  port: 6379
  password: "hellonil"
  db: 0
  pool_size: 100
cos:
  host: "https://nil-1316622710.cos.ap-nanjing.myqcloud.com"
  secret_id: "AKIDgATYN5WsPiy71oQovsd7PVO1QessdCcr"
  secret_key: "1oPvHalKgmRu9AwUs0wgDUVGn58yc5MQ"